"""Eliminando tabla rutas

Revision ID: 3ceed426bb3b
Revises: 
Create Date: 2025-06-11 20:44:48.876933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceed426bb3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('distancia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('duracion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ruta_pkey'))
    )
    # ### end Alembic commands ###
