"""Agregar direcciones a envío

Revision ID: a7a6d0a39952
Revises: 
Create Date: 2025-06-01 13:50:39.662597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a6d0a39952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_origen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('direccion_destino', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envio', schema=None) as batch_op:
        batch_op.drop_column('direccion_destino')
        batch_op.drop_column('direccion_origen')

    # ### end Alembic commands ###
